version: '3'
services:
  whatsapp-http-api:
    image: renato92/whatsapp-http-api:with-polling
    container_name: whatsapp-http-api
    build: .
    ports:
      - '3000:3000/tcp'
    environment:
      # Environment variables from https://waha.devlike.pro/docs/how-to/config/
      - WHATSAPP_HOOK_URL=https://httpbin.org/post
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    restart: always

volumes:
  mongodb_data: {}
