version: '3'
services:
  whatsapp-http-api:
    image: renato92/whatsapp-http-api:${TAG}
    container_name: whatsapp-http-api
    build:
      context: .
      dockerfile: Dockerfile.withchromium
    ports:
      - '3000:3000/tcp'
    volumes:
      - session_data:/app/.wwebjs_auth
    environment:
      # Environment variables from https://waha.devlike.pro/docs/how-to/config/
      - WHATSAPP_HOOK_URL=https://gms.church
      - WHATSAPP_HOOK_EVENTS=message
      - WHATSAPP_DEFAULT_ENGINE=WEBJS
    restart: always

volumes:
  session_data: {}
